# Generated by Django 5.1.4 on 2024-12-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headname', models.CharField(max_length=150, null=True)),
                ('companyname', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('services', models.CharField(max_length=500, null=True)),
                ('agency', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50, null=True)),
                ('receiver_mobile', models.CharField(max_length=50, null=True)),
                ('receiver_email', models.CharField(max_length=50, null=True)),
                ('receiver_address', models.CharField(max_length=50, null=True)),
                ('receiver_company', models.CharField(max_length=50, null=True)),
                ('receiver_GST', models.CharField(max_length=50, null=True)),
                ('cust_id', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, null=True)),
                ('sender_mobile', models.CharField(max_length=50, null=True)),
                ('sender_email', models.CharField(max_length=50, null=True)),
                ('sender_address', models.CharField(max_length=50, null=True)),
                ('sender_company', models.CharField(max_length=50, null=True)),
                ('sender_GST', models.CharField(max_length=50, null=True)),
                ('cust_id', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('passport', models.ImageField(max_length=50, null=True, upload_to='')),
                ('license', models.ImageField(max_length=50, null=True, upload_to='')),
                ('aadhar', models.ImageField(max_length=50, null=True, upload_to='')),
                ('location_sharing_active', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fullload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=500, null=True)),
                ('route_to', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('vehicleNo', models.CharField(max_length=500, null=True)),
                ('driverName', models.CharField(max_length=500, null=True)),
                ('tone', models.FloatField(null=True)),
                ('transport', models.CharField(max_length=500, null=True)),
                ('consignee', models.CharField(max_length=500, null=True)),
                ('consigneeMobile', models.CharField(max_length=500, null=True)),
                ('consigneeAddress', models.CharField(max_length=500, null=True)),
                ('consignor', models.CharField(max_length=500, null=True)),
                ('consignorMobile', models.CharField(max_length=500, null=True)),
                ('consignorAddress', models.CharField(max_length=500, null=True)),
                ('total', models.FloatField(null=True)),
                ('goods', models.CharField(max_length=500, null=True)),
                ('dedicationReason', models.CharField(max_length=500, null=True)),
                ('advance', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('remark', models.CharField(max_length=250, null=True)),
                ('loadId', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('paidAmt', models.FloatField(null=True)),
                ('haltAmt', models.FloatField(null=True)),
                ('dedicationAmt', models.FloatField(null=True)),
                ('finalBalance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fullloadexpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Reason', models.CharField(max_length=150, null=True)),
                ('Amount', models.CharField(max_length=150, null=True)),
                ('staffname', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=150, null=True)),
                ('staffPhone', models.CharField(max_length=150, null=True)),
                ('staffaddress', models.CharField(max_length=150, null=True)),
                ('aadhar', models.CharField(max_length=150, null=True)),
                ('staffid', models.CharField(max_length=150, null=True)),
                ('Branch', models.CharField(max_length=150, null=True)),
                ('passbook', models.CharField(max_length=150, null=True)),
                ('passbookphoto', models.CharField(max_length=150, null=True)),
                ('passport', models.CharField(max_length=150, null=True)),
                ('branchemail', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, null=True)),
                ('rccard', models.ImageField(max_length=50, null=True, upload_to='')),
                ('rccardate', models.DateField(null=True)),
                ('incurence', models.ImageField(max_length=50, null=True, upload_to='')),
                ('incurencedate', models.DateField(null=True)),
                ('permit', models.ImageField(max_length=50, null=True, upload_to='')),
                ('permitdate', models.DateField(null=True)),
                ('tax', models.ImageField(max_length=50, null=True, upload_to='')),
                ('taxdate', models.DateField(null=True)),
                ('emission', models.ImageField(max_length=50, null=True, upload_to='')),
                ('emissiondate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('location_sharing_active', models.BooleanField(default=False, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='consign_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.FloatField(null=True)),
                ('dedicationAmt', models.FloatField(null=True)),
                ('loadId', models.IntegerField(null=True)),
                ('remark', models.TextField()),
                ('dedicationamtReason', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('full_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.fullload')),
            ],
        ),
    ]
