# Generated by Django 5.1.4 on 2024-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0002_account_addconsignment_addconsignmenttemp_addtrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='door_chare',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='hamali',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='receiver_GST',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='receiver_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='receiver_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='route_from',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='route_to',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='sender_GST',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='sender_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='st_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='weightRate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
