# Generated by Django 5.1.4 on 2024-12-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_collection_door_chare_collection_freight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='door_chare',
            new_name='door_charge',
        ),
    ]
