# Generated by Django 5.1.4 on 2024-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0004_rename_door_chare_collection_door_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
